use serde::{Deserialize, Serialize};
use super::common::{GenerationRequest};


#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Default, Deserialize, Serialize, schemars::JsonSchema)]
pub struct ImageGenerationRequest {
    /// Input can be a string, array of strings, tokens, or batch inputs
    pub prompt: String,

    /// optional "transparent" or "opaque" or "auto"
    // Allows to set transparency for the background of the generated image(s).
    // This parameter is only supported for the GPT image models.
    // Must be one of transparent, opaque or auto (default value).
    // When auto is used, the model will automatically determine the best background for the image.
    pub background: Option<String>,

    /// ID of the model to use
    pub model: String,

    /// Optional "low" or "auto"
    // Control the content-moderation level for images generated by the GPT image models.
    // Must be either low for less restrictive filtering or auto (default value).
    pub moderation: Option<String>,

    /// Optional number
    // The number of images to generate. Must be between 1 and 10.
    // For dall-e-3, only n=1 is supported.
    // minimum1, maximum10
    pub n: Option<u8>,

    /// optional number
    // The compression level (0-100%) for the generated images.
    // This parameter is only supported for the GPT image models with the webp or jpeg output formats,
    // and defaults to 100.
    pub output_compression: Option<u8>,

    /// Optional "png" or "jpeg" or "webp"
    // The format in which the generated images are returned.
    // This parameter is only supported for the GPT image models.
    // Must be one of png, jpeg, or webp.
    pub output_format: Option<String>,

    /// partial_images: optional number
    // The number of partial images to generate.
    // This parameter is used for streaming responses that return partial images.
    // Value must be between 0 and 3.
    // When set to 0, the response will be a single image sent in one streaming event.
    // Note that the final image may be sent before the full number of partial images are generated if the full image is generated more quickly.
    // maximum 3, minimum 0
    pub partial_images: Option<u8>,

    /// quality: optional "standard" or "hd" or "low" or "medium" or "high" or "auto"
    // The quality of the image that will be generated.
    // auto (default value) will automatically select the best quality for the given model.
    // high, medium and low are supported for the GPT image models.
    // hd and standard are supported for dall-e-3.
    // standard is the only option for dall-e-2.
    pub quality: Option<String>,

    /// response_format: optional "url" or "b64_json"
    // The format in which generated images with dall-e-2 and dall-e-3 are returned.
    // Must be one of url or b64_json.
    // URLs are only valid for 60 minutes after the image has been generated.
    // This parameter isn’t supported for the GPT image models, which always return base64-encoded images.
    pub response_format: Option<String>,

    /// size: optional string or "auto" or "1024x1024" or "1536x1024" or 5 more
    // The size of the generated images.
    // For gpt-image-2 and gpt-image-2-2026-04-21, arbitrary resolutions are supported as WIDTHxHEIGHT strings, for example 1536x864.
    // Width and height must both be divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1.
    // Resolutions above 2560x1440 are experimental, and the maximum supported resolution is 3840x2160.
    // The requested size must also satisfy the model’s current pixel and edge limits.
    // The standard sizes 1024x1024, 1536x1024, and 1024x1536 are supported by the GPT image models;
    // auto is supported for models that allow automatic sizing.
    // For dall-e-2, use one of 256x256, 512x512, or 1024x1024.
    // For dall-e-3, use one of 1024x1024, 1792x1024, or 1024x1792.
    pub size: Option<String>,

    /// stream: optional boolean
    // Generate the image in streaming mode. Defaults to false.
    // See the Image generation guide for more information.
    // This parameter is only supported for the GPT image models.
    pub stream: Option<String>,

    /// style: optional "vivid" or "natural"
    // The style of the generated images.
    // This parameter is only supported for dall-e-3.
    // Must be one of vivid or natural.
    // Vivid causes the model to lean towards generating hyper-real and dramatic images.
    // Natural causes the model to produce more natural, less hyper-real looking images.
    pub style: Option<String>,

    /// Optional user identifier
    pub user: Option<String>,
}

impl GenerationRequest for ImageGenerationRequest {
    fn is_stream(&self) -> bool {
        self.stream.is_some()
    }

    fn get_model(&self) -> Option<&str> {
        Some(&self.model)
    }

    fn extract_text_for_routing(&self) -> String {
        // todo cache
        self.prompt.clone()
    }
}

#[derive(Serialize, Deserialize)]
struct InputTokensDetails {
    pub text_tokens: i64,
    pub image_tokens: i64,
}

#[derive(Serialize, Deserialize)]
struct Usage {
    pub total_tokens: i64,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub input_tokens_details: InputTokensDetails,
}

#[derive(Serialize, Deserialize)]
struct ImageObject {
    /// b64_json: optional string
    // The base64-encoded JSON of the generated image.
    // Returned by default for the GPT image models, and only present if response_format is set to b64_json for dall-e-2 and dall-e-3.
    pub b64_json: String,

    /// revised_prompt: optional string
    // For dall-e-3 only, the revised prompt that was used to generate the image.
    pub revised_prompt: Option<String>,

    /// url optional string
    // When using dall-e-2 or dall-e-3, the URL of the generated image if response_format is set to url (default value).
    // Unsupported for the GPT image models.
    // format: uri
    pub url: Option<String>,
}

#[derive(Serialize, Deserialize)]
struct ImageGenerationResponse {
    /// created: number
    // The Unix timestamp (in seconds) of when the image was created.
    // format: unixtime
    pub created: i64,

    /// background: optional "transparent" or "opaque"
    // The background parameter used for the image generation. Either transparent or opaque.
    pub background: Option<String>,

    /// data: optional array of Image { b64_json, revised_prompt, url }
    // The list of generated images.
    pub data: Vec<ImageObject>,

    /// output_format: optional "png" or "webp" or "jpeg"
    // The output format of the image generation. Either png, webp, or jpeg.
    pub output_format: Option<String>,

    /// quality: optional "low" or "medium" or "high"
    // The quality of the image generated. Either low, medium, or high.
    pub quality: Option<String>,

    /// size: optional "1024x1024" or "1024x1536" or "1536x1024"
    // The size of the image generated. Either 1024x1024, 1024x1536, or 1536x1024
    pub size: Option<String>,

    /// optional { input_tokens, input_tokens_details, output_tokens, 2 more }
    // For gpt-image-1 only, the token usage information for the image generation.
    pub usage: Option<Usage>,
}


#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Deserialize, Serialize, schemars::JsonSchema)]
pub enum Mask {
    FileId { file_id: String },
    ImageUrl { image_url: String },
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Default, Deserialize, Serialize, schemars::JsonSchema)]
pub struct ImageEditRequest {
    // images: array of { file_id, image_url }
    // Input image references to edit. For GPT image models, you can provide up to 16 images.

    // prompt: string
    // A text description of the desired image edit.
    // minLength1
    // maxLength32000
    pub prompt: String,

    // background: optional "transparent" or "opaque" or "auto"
    // Background behavior for generated image output.
    pub background: Option<String>,

    // input_fidelity: optional "high" or "low"
    // Controls fidelity to the original input image(s).
    pub input_fidelity: Option<String>,

    // mask: optional { file_id, image_url }
    // Reference an input image by either URL or uploaded file ID.
    // Provide exactly one of image_url or file_id.
    pub mask: Option<Mask>,

    // model: string or "gpt-image-1.5" or
    // "gpt-image-1" or "gpt-image-1-mini" or "chatgpt-image-latest"
    // The model to use for image editing.
    pub model: String,

    // moderation: optional "low" or "auto"
    // Moderation level for GPT image models.
    pub moderation: Option<String>,

    // n: optional number
    // The number of edited images to generate.
    // minimum 1, maximum 10
    pub n: Option<u8>,

    // output_compression: optional number
    // Compression level for jpeg or webp output.
    // minimum 0, maximum 100
    pub output_compression: Option<u8>,

    // output_format: optional "png" or "jpeg" or "webp"
    // Output image format. Supported for GPT image models.
    pub output_format: Option<String>,

    // partial_images: optional number
    // The number of partial images to generate.
    // This parameter is used for streaming responses that return partial images.
    // Value must be between 0 and 3.
    // When set to 0, the response will be a single image sent in one streaming event.
    // Note that the final image may be sent before the full number of partial images are generated
    // if the full image is generated more quickly.
    // maximum3
    // minimum0
    pub partial_images: Option<u8>,

    // quality: optional "low" or "medium" or "high" or "auto"
    // Output quality for GPT image models.
    pub quality: Option<String>,

    // size: optional "auto" or "1024x1024" or "1536x1024" or "1024x1536"
    // Requested output image size.
    pub size: Option<String>,

    // stream: optional boolean
    // Stream partial image results as events.
    pub stream: Option<bool>,

    // user: optional string
    // A unique identifier representing your end-user, which can help OpenAI monitor and detect abuse.
    pub user: Option<String>,
}

impl GenerationRequest for ImageEditRequest {
    fn is_stream(&self) -> bool {
        self.stream.is_some()
    }

    fn get_model(&self) -> Option<&str> {
        Some(&self.model)
    }

    fn extract_text_for_routing(&self) -> String {
        // todo cache
        self.prompt.clone()
    }
}

/// Binary image payload for `/v1/images/edits`.
///
/// The transcription endpoint uses multipart/form-data, so the file bytes
/// travel alongside the JSON-like `TranscriptionRequest` rather than inside it.
#[derive(Debug, Clone)]
pub struct ImageFile {
    /// Raw image bytes ("png" or "jpeg" or "webp").
    pub bytes: bytes::Bytes,
    /// Original filename from the multipart part. Forwarded verbatim to the worker.
    pub file_name: String,
    /// Original content-type of the image part (e.g. `image/png`), if the client supplied one.
    pub content_type: Option<String>,
}
