apiVersion: v1
kind: Secret
metadata:
  name: github-arc-secret
  namespace: actions-runner-system
type: Opaque
stringData:
  github_app_id: "<github-app-id>"
  github_app_installation_id: "<github-app-installation-id>"
  github_app_private_key: "<github-app-private-key>"
